linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - gosimple
    - unused
  disable:
    - errcheck  # We have custom error handling

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  timeout: 5m
  go: "1.20"  # Minimum supported version

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - goconst