name: Test Release Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.goreleaser.yml'
      - '.github/workflows/release.yml'

jobs:
  test-goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          
      - name: Test GoReleaser Configuration
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries
          path: dist/
          retention-days: 1